export const baseQuestions = [
  "候选人最快到岗时间是多久？",
  "每周可以稳定实习几天？",
  "可接受的整体实习时长为多久？",
  "在岗位 base 工作地点是否有稳定住所？",
];

export const seedJobs = [
  {
    id: "job-1",
    title: "排班实习生",
    department: "运营支持部",
    location: "北京",
    updatedAt: "刚刚",
    jd: "协助业务排班、数据统计、异常跟进和跨团队沟通，维护排班台账并输出周度复盘。",
    persona: "本科及以上，Excel 熟练，细心负责，沟通推进能力强；有数据分析、排班或运营支持经历优先。",
    keywords: ["Excel", "排班", "数据分析", "运营支持", "沟通", "复盘"],
  },
  {
    id: "job-2",
    title: "增长运营实习生",
    department: "用户增长部",
    location: "上海",
    updatedAt: "昨天 18:42",
    jd: "负责活动策划、用户分层运营、社群增长和数据复盘。",
    persona: "本科及以上，熟悉 Excel/SQL，有内容运营或校园推广经验优先。",
    keywords: ["活动策划", "用户增长", "数据分析", "社群运营", "Excel", "SQL"],
  },
  {
    id: "job-3",
    title: "商业分析实习生",
    department: "战略与经营",
    location: "深圳",
    updatedAt: "06-24 14:05",
    jd: "支持行业研究、经营指标分析、专题分析和汇报材料制作。",
    persona: "本科及以上，商科、统计或计算机背景，有 SQL/Python 项目经验优先。",
    keywords: ["行业研究", "商业分析", "Excel", "SQL", "Python", "建模"],
  },
];

const samples = [
  {
    id: "sample-1",
    name: "邬宜璇",
    degree: "本科",
    school: "大连民族大学",
    major: "统计学",
    graduationYear: "2028",
    years: 0.3,
    skills: ["Python", "SQL", "Excel", "Power BI", "数据分析"],
    summary: "统计学本科在读，有数据治理、风险建模和可视化项目经历。",
    experiences: ["区统计局数据专员实习：维护项目台账，搭建异常检测脚本和月度看板。"],
    projects: ["信用风险评分卡、物流风险识别、文旅吸引力建模。"],
    fileName: "【排班实习生_北京 150-180元_天】邬宜璇 28年应届生.pdf",
  },
  {
    id: "sample-2",
    name: "林芷晴",
    degree: "本科",
    school: "复旦大学",
    major: "市场营销",
    graduationYear: "2027",
    years: 0.8,
    skills: ["Excel", "活动策划", "用户增长", "社群运营"],
    summary: "有校园活动和社群运营经验，擅长数据复盘。",
    experiences: ["互联网增长运营实习，负责活动排期、用户触达和周报。"],
    projects: ["校园推广项目覆盖 12 所高校。"],
    fileName: "林芷晴-增长运营实习生.pdf",
  },
  {
    id: "sample-3",
    name: "周亦辰",
    degree: "硕士",
    school: "上海交通大学",
    major: "数据科学",
    graduationYear: "2027",
    years: 1.2,
    skills: ["SQL", "Python", "数据分析", "Tableau"],
    summary: "数据科学硕士，有用户分层和增长实验经验。",
    experiences: ["策略分析实习，负责指标监控和实验复盘。"],
    projects: ["用户流失预警模型。"],
    fileName: "周亦辰_数据分析.pdf",
  },
  {
    id: "sample-4",
    name: "许嘉宁",
    degree: "大专",
    school: "上海出版印刷高等专科学校",
    major: "数字媒体",
    graduationYear: "2026",
    years: 1.5,
    skills: ["内容运营", "活动执行", "社群维护"],
    summary: "内容执行经验丰富，学历明确为大专。",
    experiences: ["新媒体运营实习，负责内容排期和社群维护。"],
    projects: [],
    fileName: "许嘉宁-内容运营.pdf",
  },
  {
    id: "sample-5",
    name: "陈一诺",
    degree: "本科",
    school: "浙江大学",
    major: "信息管理",
    graduationYear: "2027",
    years: 0.6,
    skills: ["AI", "PRD", "Figma", "用户访谈"],
    summary: "AI 产品方向，有需求调研和原型设计经历。",
    experiences: ["AI 产品实习，协助模型效果评估。"],
    projects: ["智能客服产品原型。"],
    fileName: "陈一诺_AI产品.pdf",
  },
  {
    id: "sample-6",
    name: "何若川",
    degree: "待确认",
    school: "学历待确认",
    major: "",
    graduationYear: "",
    years: 2,
    skills: ["Excel", "排班", "沟通", "运营支持"],
    summary: "运营支持经验匹配，但简历未明确写出学历。",
    experiences: ["负责 120 人团队的周排班和异常协调。"],
    projects: [],
    fileName: "何若川_运营支持简历.pdf",
  },
  {
    id: "sample-7",
    name: "沈知微",
    degree: "硕士",
    school: "香港中文大学",
    major: "商业分析",
    graduationYear: "2026",
    years: 1,
    skills: ["商业分析", "Excel", "SQL", "Python"],
    summary: "商业分析背景，逻辑和数据能力突出。",
    experiences: ["咨询实习，负责行业研究和经营分析。"],
    projects: ["零售经营指标诊断。"],
    fileName: "沈知微-商业分析.pdf",
  },
  {
    id: "sample-8",
    name: "顾思远",
    degree: "本科",
    school: "北京工业大学",
    major: "工商管理",
    graduationYear: "2027",
    years: 0.4,
    skills: ["Excel", "沟通", "活动执行"],
    summary: "基础条件达标，岗位专项经验需要补充核实。",
    experiences: ["校学生会活动执行。"],
    projects: [],
    fileName: "【运营实习生_北京】顾思远 27届.pdf",
  },
];

export const seedResumes = {
  "job-1": samples.map((item) => ({
    ...item,
    text: [item.summary, ...item.experiences, ...item.projects, item.skills.join(" ")].join("\n"),
    parseStatus: "sample",
    confidence: 96,
    source: "示例",
    createdAt: "示例数据",
  })),
  "job-2": samples.slice(1, 6).map((item) => ({
    ...item,
    text: [item.summary, ...item.experiences, ...item.projects, item.skills.join(" ")].join("\n"),
    parseStatus: "sample",
    confidence: 94,
    source: "示例",
    createdAt: "示例数据",
  })),
  "job-3": samples.slice(2, 8).map((item) => ({
    ...item,
    text: [item.summary, ...item.experiences, ...item.projects, item.skills.join(" ")].join("\n"),
    parseStatus: "sample",
    confidence: 95,
    source: "示例",
    createdAt: "示例数据",
  })),
};
